---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: backups
spec:
  namespaceSelector:
    matchNames:
      - backups
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: velero
  endpoints:
    - port: monitoring
      interval: 60s
