# TODO: istio-injection=disabled due to velero failure which required further investigation
---
apiVersion: v1
kind: Namespace
metadata:
  name: backups
  labels:
    namespace: backups
    istio-injection: disabled
