---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/xunholy/k8s-gitops.git
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/clusters/production
    !/namespaces/base
    !/namespaces/production
    /namespaces/**/*.md
