---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: istio-system
spec:
  dnsNames:
    - gke.raspbernetes.com
    - '*.gke.raspbernetes.com'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 4.5.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 10m
  values:
    policy: upsert-only
    cloudflare:
      proxied: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.helm.sh/stable
      chart: oauth2-proxy
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      tag: v5.1.1-amd64
    extraArgs:
      oidc-issuer-url: https://dex.gke.raspbernetes.com
      cookie-domain: .raspbernetes.com
      whitelist-domain: .raspbernetes.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.helm.sh/stable
      chart: dex
      version: 2.15.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 10m
  values:
    certs:
      image: gcr.io/google_containers/kubernetes-dashboard-init-arm
    config:
      issuer: https://dex.gke.raspbernetes.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # CRDs are applied in core/crd/kube-prometheus-stack.yaml
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 13.4.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 10m
  values:
    grafana:
      grafana.ini:
        server:
          root_url: https://grafana.gke.raspbernetes.com
        auth.generic_oauth:
          auth_url: https://dex.gke.raspbernetes.com/auth
          token_url: https://dex.gke.raspbernetes.com/token
          api_url: https://dex.gke.raspbernetes.com/userinfo
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'grafana.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'auth.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'dex.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'sealed-secrets.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos
  namespace: observability
spec:
  hosts:
    - 'thanos.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: observability
spec:
  hosts:
    - 'kiali.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: receiver
  namespace: flux-system
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'receiver.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
  namespace: istio-system
spec:
  hosts:
    - 'jaeger.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hubble-ui
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'hubble.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: observability
spec:
  hosts:
    - 'prometheus.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alert-manager
  namespace: observability
spec:
  hosts:
    - 'alert-manager.gke.raspbernetes.com'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dex-helm-values
  namespace: network
spec:
  encryptedData:
    values.yaml: AgB8yTZf4b5JTIfG/EeH4+0vjM0DX2kwsBkfw2s7GG/lPD7nJXX/pnQ4s5PnBbwMpeCmyFj8KcsmdCv9jbd2+YXyfmZICrwbhtFYv/OuX/LWC1SAsCpMB3WDjJE5Wpp8C/lNEwTZ5p/AIuW+T+d/1qW1hmlcI6UETcIAjzpnW94ieCx8jeGfd+fdDMshooSWanZzYwPbsKjUe0n3GDwjlNM0r7Kxm49yGE74WTfT0XaPDK7xGdbwIZkVigA6zEyFsOQwN/WkLirknMTBO+7W94HWESStqhUCSxMM0raGq/zBoUKrjZ3r98p0sAONKfDhVhy3JyzW1vBLVi/WeNyBzlyqRfIClqQuVKr34k+DktmiOT4FJ5XCb1KjLJ79bkslQxW5Y7kd7XOoGvI+jh2feoKMAK483ebyl1A6s65udPHANQpsscfUDlcKohE8MGCeP7AmGl6eUmVtUB5sTP589tmRcTJiantkhc6DrIgPnGV60I7g6me9wv4HqakWJDWmKG0/z8Qx6KaD8KjhCrc5LyXOQbuCHSpSrVOwmD+REQ79+4QF1mNDdKq8B6o7E2hkqzCh+KaB2jvzaBO5m1t/hbcp3kY13wHuS36cxX0AvGiTdRdMMm7527SksQ2IaOPUQTW60CsRPEXDEcTzhUltPsdDcJKrBGq3vYtdiJ/PjYsNtE9yV11tyBA+0vaJ/3EJFH5O+z6pxJoCIXQGxTKy11SeHlOpQaLFbT2p6sPA2Beh47j9NiGvpHUblAjaVOm+sFOP/KClXoVJGkFiVREnDuirfPO+uC1O74XR7DnIrLVlvnuClguzAdEZXgyfi28wiyv4r04tj+KvfuvBgm4xyAl5lr6hqjwya8AmHPm2gqo+FGSFwhfWglhu/eEvNyAGNmh1Y+VAHPU/w5KPba5peuMxmZJMwan+MhFujTfx3fB72ZBK6si+8zU81fe690xOpAPVFSiPe0ZEyXuzxFcVysxeO+E+VoU6NBxAmprVvJSnWeCU1CXHg4Z6q0oPCGCDa0bxTPQ22dzflGr35O4l1y/bAZkaY0zjVFbQqYrqAECHNg7kg8cd3Q3PRsX8ATiJgSSZdNOF4qMF6lOAq8SbYNLPNTpTYYIuus0LALci/I6sVtwIHFe9UZ1Esd9VcisfE/L6gqZobPPgKnxSzexXC41q8abzgws0Ob6ACk5RECZw4Y5JUOlOvkjd5pKO6vv3A9fQGmvDeZVrilnLYAMmXef2O7XCCKX0Gj0OzPVVgFyIb9S9n7mEISWl6LyHFJ3Juc6ww8NXPoyd0Y8ghpSy3tsud4oNpfmGnwGdD+gGKp4ddb8xueZ4WguVC13fogbsS5/JD7IjJSdrfe0wGw3EhfRc8hyg2rETbTLHWK9J7MSLxPdqrdq29qo2Fn0/S8i4yOCxNh7hp0rrbi4LfZqD+9xapiPKzpi9eJdJu+EXM/ehkLRr9mEfAfH0nt/tewoZchDqMveX/rgQLBNDavlcKJwZSeqKpLby/yepi0cKQ0UbqvdcRZNAaiQcl2CKl5l2syYOKcvF0gyDSil4FlmCpWrL3RjGeVEFjTpqLJTlmYIJQAd2nDxl5Gj72tVxKSTzKolu4/jqCk07Frp3u2PJteWK3RRWca+vmd8qGK9Mryc5bcU46lJCLeZCvkEzvoccmP2CzxpJzPi7+EXXnkhDol0uRd0b9xXnNMetfqE38dEt37dHvkm2Br2hocD5CEUlaTCLRGOL7LRf4reDxHDEeIewKV+X6c46wtXueIYiL2l/MBVQHVt86P8kuftFopz3vg0mxE5VwPyTX23fCr9ingd38/9rLCbbrBRSwbsooaOWmuQ4RoMCWYsXyMvA8dh8gC3Qps56MTH2gJq20u8ptV35fqKPTmDsZf21tpoFZOIeUAA5Q8LYbhcz6m8ISZ92IKtS+zsjUtYwEGKEIut5lfFxLRI93ScqAC2mMTf9SZl7zdtG0b08jicuyR5Hy0RQkEEZvMCVtgT7qOwcvsIMYtJRQ3x6SloMO4r5bhtt5/oYLyQUI7zYOerWC4dtXkvLdlzueVr+t1O+PGY88RJnpEUKJsUE52a1f7f/FCPX5lZOqmyzsW9/NcEIZuwLGmtY1mbpZIdaEX1VQ1CUbG3YifXlRgNmg+BgYyD+GR0tDkx8HhXEt+4COzrL97zK5Y6GPdzFJ8AwUw/1C+hSHsi/n8IvUREmGI2wCHg5XtwgukE2GXMnhG+6Lc2fNBBpYC2bxlVAqDo=
