---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.helm.sh/stable
      chart: oauth2-proxy
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      tag: v5.1.1-amd64
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-system-ingress-gateway
  namespace: 'istio-system'
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*.gke.raspbernetes.com'
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - '*.gke.raspbernetes.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/target: gke.raspbernetes.com
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  hosts:
    - 'grafana.gke.raspbernetes.com'
