apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: runner
  namespace: actions-runner-system
spec:
  organization: raspbernetes
  image: docker.io/summerwind/actions-runner:v2.273.5
  env: []
