name: flux

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flux CLI
        run: brew install fluxcd/tap/flux

      - name: Run Flux Auto-Update
        run: ./bootstrap/update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/flux
          title: Auto-update flux version
          commit-message: Auto-update flux version
          body: |
            Update flux version of tools
          labels: dependencies
